--- #YAML:1.0
name:               WWW-Mixi-Scraper
version:            0.33
abstract:           yet another mixi scraper
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               0
    Exporter:             0
    Module::Find:         0
    String::CamelCase:    0
    Test::UseAllModules:  0.09
    Time::HiRes:          0
    URI:                  0
    URI::QueryParam:      0
    Web::Scraper:         0.17
    WWW::Mechanize:       1.50
resources:
    repository:  http://github.com/charsbar/www-mixi-scraper/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
