--- #YAML:1.0
name:                WWW-Mixi-Scraper
version:             0.07
abstract:            yet another mixi scraper
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Encode:                        0
    Module::Pluggable::Fast:       0
    String::CamelCase:             0
    Test::UseAllModules:           0
    Time::HiRes:                   0
    URI:                           0
    URI::QueryParam:               0
    Web::Scraper:                  0
    WWW::Mechanize:                1.30
    WWW::Mechanize::DecodedContent: 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
